### ISSUE TITLE
Package 'python-software-properties' has no installation candidate

### ISSUE THREAD

**Issue by jknair0** [futurice/android-jenkins-docker#2]
Reading state information...
Package python-software-properties is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  software-properties-common

E: Package 'python-software-properties' has no installation candidate
The command '/bin/sh -c apt-get update && 	apt-get install software-properties-common python-software-properties unzip -y' returned a non-zero code: 100

**Comment by aponx** [comment]
i get this problem too. What should i do?

**Comment by saitam1** [comment]
What was the solution? I get this issue too
